# Generated by Django 3.1.3 on 2021-03-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=255, verbose_name='责任人')),
                ('identity', models.CharField(max_length=255, unique=True, verbose_name='唯一性证明')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系方式')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='电子邮箱')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '项目责任人记录表',
                'db_table': 'fapd_project_in_charge',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='拥有者')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='项目名称')),
                ('stime', models.DateTimeField(verbose_name='项目开始时间')),
                ('etime', models.DateTimeField(verbose_name='项目结束时间')),
                ('dtime', models.DateTimeField(blank=True, null=True, verbose_name='项目完成时间')),
                ('budget', models.BigIntegerField(default=0, verbose_name='项目预算')),
                ('status', models.CharField(choices=[('start', '已启动'), ('plan', '规划中'), ('execute', '执行中'), ('observe', '监控中'), ('acceptance', '已验收'), ('end', '已结束')], default='start', max_length=16, verbose_name='项目状态')),
                ('in_charge', models.ManyToManyField(to='fapd.ProjectInCharge', verbose_name='责任人')),
                ('project', models.ForeignKey(blank=True, help_text='自关联，如果关联有外键，则当前实例为子项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_project', to='fapd.projectinfo')),
            ],
            options={
                'verbose_name': '项目信息表',
                'db_table': 'fapd_project_info',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='拥有者')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('plan', '计划中'), ('wip', '进行中'), ('discard', '已废弃'), ('done', '已完成')], default='plan', help_text='任务当前的状态', max_length=16, verbose_name='任务状态')),
                ('dtime', models.DateTimeField(blank=True, null=True, verbose_name='任务完成时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('in_charge', models.ManyToManyField(to='fapd.ProjectInCharge', verbose_name='责任人')),
                ('project', models.ForeignKey(help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, related_name='plan_task', to='fapd.projectinfo', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目计划任务表',
                'db_table': 'fapd_project_plan_task',
            },
        ),
    ]
