# Generated by Django 3.1.3 on 2021-03-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='拥有者')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '博客分类表',
                'db_table': 'blog_classify',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='拥有者')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '博客标签表',
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='ArticleSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='拥有者')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='系列名称')),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial', to='blog.articleclassify', verbose_name='系列分类')),
                ('tags', models.ManyToManyField(related_name='serial', to='blog.ArticleTag', verbose_name='系列标签')),
            ],
            options={
                'verbose_name': '博客文章系列表',
                'db_table': 'blog_article_serial',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='拥有者')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='文章标题')),
                ('desc', models.TextField(verbose_name='内容简介')),
                ('content', models.TextField(help_text='markdown格式的正文内容', verbose_name='文章正文')),
                ('creator', models.CharField(max_length=64, verbose_name='作者')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否发表')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('etime', models.DateTimeField(blank=True, null=True, verbose_name='编辑时间')),
                ('html_content', models.TextField(blank=True, help_text='由content转化为html格式的正文内容', null=True, verbose_name='html正文')),
                ('ptime', models.DateTimeField(blank=True, null=True, verbose_name='发表时间')),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='blog.articleclassify', verbose_name='博客分类')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='blog.articleserial', verbose_name='所属系列')),
                ('tags', models.ManyToManyField(related_name='article', to='blog.ArticleTag', verbose_name='博客标签')),
            ],
            options={
                'verbose_name': '博客文章表',
                'db_table': 'blog_article',
                'ordering': ('-id',),
            },
        ),
    ]
