# Generated by Django 3.1.3 on 2021-03-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-id',), 'verbose_name': '博客文章表'},
        ),
        migrations.AlterField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='blog.articleclassify', verbose_name='博客分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article', to='blog.ArticleTag', verbose_name='博客标签'),
        ),
        migrations.CreateModel(
            name='ArticleSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(default='admin', max_length=64, verbose_name='创建者')),
                ('owner', models.CharField(default='admin', max_length=64, verbose_name='拥有者')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='系列名称')),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial', to='blog.articleclassify', verbose_name='系列分类')),
                ('tags', models.ManyToManyField(related_name='serial', to='blog.ArticleTag', verbose_name='系列标签')),
            ],
            options={
                'verbose_name': '博客文章系列表',
                'db_table': 'blog_article_serial',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='blog.articleserial', verbose_name='所属系列'),
        ),
    ]
