# Generated by Django 3.1.3 on 2021-03-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210301_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_content',
            field=models.TextField(blank=True, help_text='由content转化为html格式的正文内容', null=True, verbose_name='html正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='markdown格式的正文内容', verbose_name='文章正文'),
        ),
    ]
